# Generated by Django 2.2.2 on 2019-06-20 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('sigla', models.IntegerField()),
            ],
            managers=[
                ('colegios', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=20)),
                ('cupos', models.IntegerField()),
                ('profesorjefe', models.CharField(max_length=20)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.Colegio')),
            ],
            managers=[
                ('cursos', django.db.models.manager.Manager()),
            ],
        ),
    ]
