# Generated by Django 2.2.2 on 2019-06-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='sigla',
        ),
    ]
